# Generated by Django 2.1.5 on 2019-05-11 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст заметки')),
                ('shorttext', models.CharField(default='Пусто', max_length=50, verbose_name='Первые символы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('deleted', models.DateField(null=True, verbose_name='Дата удаления')),
                ('locked', models.BooleanField(default=False, verbose_name='Только для чтения')),
                ('protected', models.BooleanField(default=False, verbose_name='Запрашивать пароль')),
                ('user', models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Замеки',
                'ordering': ['-edited'],
            },
        ),
    ]
